/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LexiconRouteImport } from './routes/lexicon'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as RootsIndexRouteImport } from './routes/roots/index'
import { Route as RootsRootIdRouteImport } from './routes/roots/$rootId'
import { Route as WordLemmaRouteImport } from './routes/word/$lemma'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LexiconRoute = LexiconRouteImport.update({
  id: '/lexicon',
  path: '/lexicon',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const RootsIndexRoute = RootsIndexRouteImport.update({
  id: '/roots/',
  path: '/roots/',
  getParentRoute: () => rootRouteImport,
} as any)
const RootsRootIdRoute = RootsRootIdRouteImport.update({
  id: '/roots/$rootId',
  path: '/roots/$rootId',
  getParentRoute: () => rootRouteImport,
} as any)
const WordLemmaRoute = WordLemmaRouteImport.update({
  id: '/word/$lemma',
  path: '/word/$lemma',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lexicon': typeof LexiconRoute
  '/library': typeof LibraryRoute
  '/saved': typeof SavedRoute
  '/roots/$rootId': typeof RootsRootIdRoute
  '/word/$lemma': typeof WordLemmaRoute
  '/roots/': typeof RootsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lexicon': typeof LexiconRoute
  '/library': typeof LibraryRoute
  '/saved': typeof SavedRoute
  '/roots/$rootId': typeof RootsRootIdRoute
  '/word/$lemma': typeof WordLemmaRoute
  '/roots': typeof RootsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lexicon': typeof LexiconRoute
  '/library': typeof LibraryRoute
  '/saved': typeof SavedRoute
  '/roots/$rootId': typeof RootsRootIdRoute
  '/word/$lemma': typeof WordLemmaRoute
  '/roots/': typeof RootsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/lexicon'
    | '/library'
    | '/saved'
    | '/roots/$rootId'
    | '/word/$lemma'
    | '/roots/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/lexicon'
    | '/library'
    | '/saved'
    | '/roots/$rootId'
    | '/word/$lemma'
    | '/roots'
  id:
    | '__root__'
    | '/'
    | '/lexicon'
    | '/library'
    | '/saved'
    | '/roots/$rootId'
    | '/word/$lemma'
    | '/roots/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LexiconRoute: typeof LexiconRoute
  LibraryRoute: typeof LibraryRoute
  SavedRoute: typeof SavedRoute
  RootsRootIdRoute: typeof RootsRootIdRoute
  WordLemmaRoute: typeof WordLemmaRoute
  RootsIndexRoute: typeof RootsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lexicon': {
      id: '/lexicon'
      path: '/lexicon'
      fullPath: '/lexicon'
      preLoaderRoute: typeof LexiconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roots/': {
      id: '/roots/'
      path: '/roots'
      fullPath: '/roots/'
      preLoaderRoute: typeof RootsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roots/$rootId': {
      id: '/roots/$rootId'
      path: '/roots/$rootId'
      fullPath: '/roots/$rootId'
      preLoaderRoute: typeof RootsRootIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/word/$lemma': {
      id: '/word/$lemma'
      path: '/word/$lemma'
      fullPath: '/word/$lemma'
      preLoaderRoute: typeof WordLemmaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LexiconRoute: LexiconRoute,
  LibraryRoute: LibraryRoute,
  SavedRoute: SavedRoute,
  RootsRootIdRoute: RootsRootIdRoute,
  WordLemmaRoute: WordLemmaRoute,
  RootsIndexRoute: RootsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
