import type { Affix } from "./types";

export const PREFIXES: { form: string; lang: string; sense: string }[] = [
  { form: "counter", lang: "拉丁", sense: "相反，对着" },
  { form: "circum", lang: "拉丁", sense: "环绕" },
  { form: "inter", lang: "拉丁", sense: "在……之间" },
  { form: "intra", lang: "拉丁", sense: "在……之内" },
  { form: "intro", lang: "拉丁", sense: "向内" },
  { form: "extra", lang: "拉丁", sense: "在外" },
  { form: "hyper", lang: "希腊", sense: "超过，过度" },
  { form: "hypo", lang: "希腊", sense: "在下，不足" },
  { form: "super", lang: "拉丁", sense: "在上，超越" },
  { form: "under", lang: "日耳曼", sense: "在下" },
  { form: "trans", lang: "拉丁", sense: "穿过，越过" },
  { form: "semi", lang: "拉丁", sense: "一半" },
  { form: "over", lang: "日耳曼", sense: "越过，过度" },
  { form: "fore", lang: "日耳曼", sense: "在前" },
  { form: "anti", lang: "希腊", sense: "反对" },
  { form: "auto", lang: "希腊", sense: "自己" },
  { form: "para", lang: "希腊", sense: "旁，辅助" },
  { form: "meta", lang: "希腊", sense: "在后，超越" },
  { form: "peri", lang: "希腊", sense: "周围" },
  { form: "proto", lang: "希腊", sense: "最初" },
  { form: "pseudo", lang: "希腊", sense: "假" },
  { form: "multi", lang: "拉丁", sense: "多" },
  { form: "micro", lang: "希腊", sense: "小" },
  { form: "macro", lang: "希腊", sense: "大" },
  { form: "mono", lang: "希腊", sense: "单一" },
  { form: "poly", lang: "希腊", sense: "多" },
  { form: "tele", lang: "希腊", sense: "远" },
  { form: "post", lang: "拉丁", sense: "在后" },
  { form: "pre", lang: "拉丁", sense: "在前" },
  { form: "pro", lang: "拉丁", sense: "向前，代替" },
  { form: "sub", lang: "拉丁", sense: "在下" },
  { form: "con", lang: "拉丁", sense: "共同，一起" },
  { form: "com", lang: "拉丁", sense: "共同" },
  { form: "col", lang: "拉丁", sense: "共同" },
  { form: "cor", lang: "拉丁", sense: "共同" },
  { form: "dis", lang: "拉丁", sense: "分开，否定" },
  { form: "mis", lang: "日耳曼/拉丁", sense: "错误，坏" },
  { form: "non", lang: "拉丁", sense: "不" },
  { form: "out", lang: "日耳曼", sense: "向外" },
  { form: "uni", lang: "拉丁", sense: "单一" },
  { form: "bio", lang: "希腊", sense: "生命" },
  { form: "geo", lang: "希腊", sense: "大地" },
  { form: "neo", lang: "希腊", sense: "新" },
  { form: "de", lang: "拉丁", sense: "去掉，向下，彻底" },
  { form: "re", lang: "拉丁", sense: "再，向后" },
  { form: "un", lang: "日耳曼", sense: "否定，解开" },
  { form: "in", lang: "拉丁", sense: "向内；或否定" },
  { form: "im", lang: "拉丁", sense: "向内；或否定" },
  { form: "il", lang: "拉丁", sense: "否定" },
  { form: "ir", lang: "拉丁", sense: "否定" },
  { form: "en", lang: "拉丁/法语", sense: "使成为" },
  { form: "em", lang: "拉丁/法语", sense: "使成为" },
  { form: "ex", lang: "拉丁", sense: "向外" },
  { form: "ad", lang: "拉丁", sense: "朝向" },
  { form: "ab", lang: "拉丁", sense: "离开" },
  { form: "ob", lang: "拉丁", sense: "对着" },
  { form: "se", lang: "拉丁", sense: "分开" },
  { form: "be", lang: "日耳曼", sense: "使，围绕" },
  { form: "a", lang: "希腊/英语", sense: "不；或方向" },
];

export const SUFFIXES: { form: string; lang: string; sense: string }[] = [
  { form: "ization", lang: "希腊/拉丁", sense: "使成为……的过程" },
  { form: "isation", lang: "希腊/拉丁", sense: "使成为……的过程" },
  { form: "ational", lang: "拉丁", sense: "与某一动作有关的" },
  { form: "ability", lang: "拉丁", sense: "能够被……的性质" },
  { form: "ibility", lang: "拉丁", sense: "能够被……的性质" },
  { form: "fulness", lang: "日耳曼", sense: "充满某性质" },
  { form: "lessness", lang: "日耳曼", sense: "缺少某性质" },
  { form: "istically", lang: "希腊", sense: "以某种方式" },
  { form: "ology", lang: "希腊", sense: "关于……的言说/学科" },
  { form: "ography", lang: "希腊", sense: "关于……的书写" },
  { form: "osophy", lang: "希腊", sense: "对……的爱与智慧" },
  { form: "opathy", lang: "希腊", sense: "遭受，病" },
  { form: "ometer", lang: "希腊", sense: "测量之器" },
  { form: "oscope", lang: "希腊", sense: "观看之器" },
  { form: "ectomy", lang: "希腊", sense: "切去" },
  { form: "ation", lang: "拉丁", sense: "动作凝结成的事物" },
  { form: "ition", lang: "拉丁", sense: "动作凝结成的事物" },
  { form: "sion", lang: "拉丁", sense: "动作凝结成的事物" },
  { form: "tion", lang: "拉丁", sense: "动作凝结成的事物" },
  { form: "ment", lang: "拉丁", sense: "动作的结果" },
  { form: "ness", lang: "日耳曼", sense: "性质本身" },
  { form: "less", lang: "日耳曼", sense: "没有" },
  { form: "ship", lang: "日耳曼", sense: "身份，状态" },
  { form: "hood", lang: "日耳曼", sense: "身份，状态" },
  { form: "dom", lang: "日耳曼", sense: "领域，状态" },
  { form: "ance", lang: "拉丁", sense: "过程或状态" },
  { form: "ence", lang: "拉丁", sense: "过程或状态" },
  { form: "ancy", lang: "拉丁", sense: "状态" },
  { form: "ency", lang: "拉丁", sense: "状态" },
  { form: "able", lang: "拉丁", sense: "能够被……的" },
  { form: "ible", lang: "拉丁", sense: "能够被……的" },
  { form: "ious", lang: "拉丁", sense: "具有……性质" },
  { form: "eous", lang: "拉丁", sense: "具有……性质" },
  { form: "ous", lang: "拉丁", sense: "具有……性质" },
  { form: "ive", lang: "拉丁", sense: "有……倾向" },
  { form: "ator", lang: "拉丁", sense: "施行者" },
  { form: "ary", lang: "拉丁", sense: "与……有关" },
  { form: "ery", lang: "拉丁", sense: "场所或集合" },
  { form: "ory", lang: "拉丁", sense: "场所或倾向" },
  { form: "ure", lang: "拉丁", sense: "行为或结果" },
  { form: "age", lang: "法语", sense: "集合或过程" },
  { form: "ism", lang: "希腊", sense: "体系，主张" },
  { form: "ist", lang: "希腊", sense: "从事者" },
  { form: "ize", lang: "希腊", sense: "使成为" },
  { form: "ise", lang: "希腊", sense: "使成为" },
  { form: "ify", lang: "拉丁", sense: "使成为" },
  { form: "ate", lang: "拉丁", sense: "使，或具有" },
  { form: "ical", lang: "希腊/拉丁", sense: "与……有关" },
  { form: "ial", lang: "拉丁", sense: "与……有关" },
  { form: "ual", lang: "拉丁", sense: "与……有关" },
  { form: "al", lang: "拉丁", sense: "与……有关" },
  { form: "ic", lang: "希腊", sense: "与……有关" },
  { form: "ly", lang: "日耳曼", sense: "以……的方式" },
  { form: "ful", lang: "日耳曼", sense: "充满" },
  { form: "ish", lang: "日耳曼", sense: "略带……性质" },
  { form: "ing", lang: "日耳曼", sense: "进行中" },
  { form: "ed", lang: "日耳曼", sense: "已完成" },
  { form: "er", lang: "日耳曼", sense: "施行者，或比较" },
  { form: "or", lang: "拉丁", sense: "施行者" },
  { form: "ee", lang: "法语", sense: "承受者" },
  { form: "ant", lang: "拉丁", sense: "发出动作者" },
  { form: "ent", lang: "拉丁", sense: "发出动作者" },
  { form: "ity", lang: "拉丁", sense: "抽象性质" },
  { form: "ty", lang: "拉丁", sense: "抽象性质" },
  { form: "sy", lang: "希腊", sense: "状态" },
  { form: "cy", lang: "拉丁", sense: "状态" },
  { form: "en", lang: "日耳曼", sense: "使，或材质" },
  { form: "y", lang: "日耳曼/拉丁", sense: "性质或状态" },
  { form: "s", lang: "日耳曼", sense: "复数或第三人称" },
];

export function asAffix(
  form: string,
  kind: Affix["kind"],
  lang: string,
  sense: string,
): Affix {
  return { form, kind, lang, sense };
}
