import type { LangFamily, LineageStep } from "./types";

export type LemmaHint = {
  root: string;
  family: LangFamily;
  lineage: LineageStep[];
  stem?: string;
};

export const LEMMAS_B: Record<string, LemmaHint> = {
  prison: { root: "ghend", family: "Italic", lineage: [{ lang: "拉丁语", form: "prēnsiō", gloss: "抓住" }] },
  metaphor: { root: "bher", family: "Hellenic", lineage: [{ lang: "希腊语", form: "metaphorá", gloss: "搬运到别处" }] },
  transfer: { root: "bher", family: "Italic", lineage: [{ lang: "拉丁语", form: "trānsferre", gloss: "搬过去" }] },
  refer: { root: "bher", family: "Italic", lineage: [{ lang: "拉丁语", form: "referre", gloss: "带回" }] },
  prefer: { root: "bher", family: "Italic", lineage: [{ lang: "拉丁语", form: "praeferre", gloss: "拿到前面" }] },
  birth: { root: "bher", family: "Germanic", lineage: [{ lang: "古英语", form: "gebyrd", gloss: "出生" }] },
  bear: { root: "bher", family: "Germanic", lineage: [{ lang: "古英语", form: "beran", gloss: "扛，生" }] },
  generate: { root: "gen", family: "Italic", lineage: [{ lang: "拉丁语", form: "generāre", gloss: "使出生" }] },
  genesis: { root: "gen", family: "Hellenic", lineage: [{ lang: "希腊语", form: "génesis", gloss: "起源，生成" }] },
  nation: { root: "gen", family: "Italic", lineage: [{ lang: "拉丁语", form: "nātiō", gloss: "出生在一起的人们" }] },
  pregnant: { root: "gen", family: "Italic", lineage: [{ lang: "拉丁语", form: "praegnāns", gloss: "生之前" }] },
  kind: { root: "gen", family: "Germanic", lineage: [{ lang: "古英语", form: "cynd", gloss: "出身，种类" }] },
  king: { root: "gen", family: "Germanic", lineage: [{ lang: "古英语", form: "cyning", gloss: "族人中的那一个" }] },
  kin: { root: "gen", family: "Germanic", lineage: [{ lang: "古英语", form: "cynn", gloss: "亲族" }] },
  yoga: { root: "yeug", family: "Sanskrit", lineage: [{ lang: "梵语", form: "yoga", gloss: "轭；相应" }] },
  join: { root: "yeug", family: "Italic", lineage: [{ lang: "拉丁语", form: "iungere", gloss: "轭在一起" }] },
  religion: { root: "bhendh", family: "Italic", lineage: [{ lang: "拉丁语", form: "religiō / religāre", gloss: "再绑上；敬畏" }] },
  peace: { root: "pag", family: "Italic", lineage: [{ lang: "拉丁语", form: "pāx", gloss: "被钉牢的约定" }] },
  pact: { root: "pag", family: "Italic", lineage: [{ lang: "拉丁语", form: "pactum", gloss: "钉住的协议" }] },
  faith: { root: "bheidh", family: "Italic", lineage: [{ lang: "拉丁语", form: "fidēs", gloss: "信任" }] },
  federal: { root: "bheidh", family: "Italic", lineage: [{ lang: "拉丁语", form: "foedus", gloss: "盟约" }] },
  just: { root: "yewes", family: "Italic", lineage: [{ lang: "拉丁语", form: "iūstus", gloss: "合乎 fas 的" }] },
  jury: { root: "yewes", family: "Italic", lineage: [{ lang: "拉丁语", form: "iūrāre", gloss: "起誓" }] },
  injury: { root: "yewes", family: "Italic", lineage: [{ lang: "拉丁语", form: "iniūria", gloss: "不法" }] },
  sacred: { root: "sak", family: "Italic", lineage: [{ lang: "拉丁语", form: "sacer", gloss: "被分出的，神圣/可咒" }] },
  sacrifice: { root: "sak", family: "Italic", lineage: [{ lang: "拉丁语", form: "sacrificium", gloss: "使成为神圣" }] },
  state: { root: "sta", family: "Italic", lineage: [{ lang: "拉丁语", form: "status", gloss: "站立的姿态" }] },
  status: { root: "sta", family: "Italic", lineage: [{ lang: "拉丁语", form: "status", gloss: "站姿，地位" }] },
  system: { root: "sta", family: "Hellenic", lineage: [{ lang: "希腊语", form: "sýstēma", gloss: "被放在一起的整体" }] },
  institute: { root: "sta", family: "Italic", lineage: [{ lang: "拉丁语", form: "instituere", gloss: "放进去使站住" }] },
  destiny: { root: "sta", family: "Italic", lineage: [{ lang: "拉丁语", form: "dēstināre", gloss: "使固定" }] },
  substance: { root: "sta", family: "Italic", lineage: [{ lang: "拉丁语", form: "substantia", gloss: "站在下面的" }] },
  way: { root: "wegh", family: "Germanic", lineage: [{ lang: "古英语", form: "weg", gloss: "路" }] },
  vehicle: { root: "wegh", family: "Italic", lineage: [{ lang: "拉丁语", form: "vehicula", gloss: "运载之器" }] },
  voyage: { root: "wegh", family: "Italic", lineage: [{ lang: "拉丁语", form: "viāticum", gloss: "路上的" }] },
  obvious: { root: "wegh", family: "Italic", lineage: [{ lang: "拉丁语", form: "obvius", gloss: "挡在路上的" }] },
  experience: { root: "per", family: "Italic", lineage: [{ lang: "拉丁语", form: "experīrī", gloss: "穿过试炼" }] },
  experiment: { root: "per", family: "Italic", lineage: [{ lang: "拉丁语", form: "experimentum", gloss: "试穿" }] },
  fear: { root: "per", family: "Germanic", lineage: [{ lang: "古英语", form: "fǣr", gloss: "突然的灾；恐惧" }] },
  first: { root: "per", family: "Germanic", lineage: [{ lang: "古英语", form: "fyrst", gloss: "最前" }] },
  father: { root: "per", family: "Germanic", lineage: [{ lang: "古英语", form: "fæder", gloss: "父" }] },
  mother: { root: "gen", family: "Germanic", lineage: [{ lang: "古英语", form: "mōdor", gloss: "母" }] },
  brother: { root: "bher", family: "Germanic", lineage: [{ lang: "古英语", form: "brōþor", gloss: "兄弟" }] },
  sister: { root: "sem", family: "Germanic", lineage: [{ lang: "古英语", form: "sweostor", gloss: "姐妹" }] },
  friend: { root: "leubh", family: "Germanic", lineage: [{ lang: "古英语", form: "frēond", gloss: "爱着的人" }] },
  free: { root: "leubh", family: "Germanic", lineage: [{ lang: "古英语", form: "frēo", gloss: "亲爱的，自由的" }] },
  work: { root: "werg", family: "Germanic", lineage: [{ lang: "古英语", form: "weorc", gloss: "工作" }] },
  energy: { root: "werg", family: "Hellenic", lineage: [{ lang: "希腊语", form: "enérgeia", gloss: "在工作中" }] },
  organ: { root: "werg", family: "Hellenic", lineage: [{ lang: "希腊语", form: "órganon", gloss: "工具" }] },
  surgery: { root: "werg", family: "Hellenic", lineage: [{ lang: "希腊语", form: "kheirourgía", gloss: "手的工作" }] },
  light: { root: "leuk", family: "Germanic", lineage: [{ lang: "古英语", form: "lēoht", gloss: "光" }] },
  lucid: { root: "leuk", family: "Italic", lineage: [{ lang: "拉丁语", form: "lūcidus", gloss: "明亮的" }] },
  illuminate: { root: "leuk", family: "Italic", lineage: [{ lang: "拉丁语", form: "illūmināre", gloss: "照亮" }] },
  photograph: { root: "bha", family: "Hellenic", lineage: [{ lang: "希腊语", form: "phōs + gráphein", gloss: "用光刮写" }] },
  fantasy: { root: "bha", family: "Hellenic", lineage: [{ lang: "希腊语", form: "phantasía", gloss: "使显现" }] },
  phone: { root: "bha", family: "Hellenic", lineage: [{ lang: "希腊语", form: "phōnḗ", gloss: "声音" }] },
  voice: { root: "wekw", family: "Italic", lineage: [{ lang: "拉丁语", form: "vōx", gloss: "声音" }] },
  vocabulary: { root: "wekw", family: "Italic", lineage: [{ lang: "拉丁语", form: "vocābulum", gloss: "称呼" }] },
  epic: { root: "wekw", family: "Hellenic", lineage: [{ lang: "希腊语", form: "épos", gloss: "言，诗行" }] },
  psychology: { root: "psych", family: "Hellenic", lineage: [{ lang: "希腊语", form: "psykhḗ + lógos", gloss: "关于灵魂的言" }] },
  animal: { root: "ane", family: "Italic", lineage: [{ lang: "拉丁语", form: "animāl", gloss: "有气者" }] },
  atmosphere: { root: "ane", family: "Hellenic", lineage: [{ lang: "希腊语", form: "atmós + sphaîra", gloss: "蒸汽之球" }] },
  cosmos: { root: "cosm", family: "Hellenic", lineage: [{ lang: "希腊语", form: "kósmos", gloss: "秩序，妆饰，世界" }] },
  cosmetic: { root: "cosm", family: "Hellenic", lineage: [{ lang: "希腊语", form: "kosmētikós", gloss: "安排、妆饰的" }] },
  chaos: { root: "eu", family: "Hellenic", lineage: [{ lang: "希腊语", form: "kháos", gloss: "裂口，混茫" }] },
  theology: { root: "theos", family: "Hellenic", lineage: [{ lang: "希腊语", form: "theología", gloss: "关于神的言" }] },
  enthusiasm: { root: "theos", family: "Hellenic", lineage: [{ lang: "希腊语", form: "enthousiasmós", gloss: "神在里面" }] },
  biology: { root: "bios", family: "Hellenic", lineage: [{ lang: "希腊语", form: "bíos + lógos", gloss: "关于生命的言" }] },
  geography: { root: "geo", family: "Hellenic", lineage: [{ lang: "希腊语", form: "geōgraphía", gloss: "书写大地" }] },
  geometry: { root: "geo", family: "Hellenic", lineage: [{ lang: "希腊语", form: "geōmetría", gloss: "量地" }] },
  hydrogen: { root: "hydr", family: "Hellenic", lineage: [{ lang: "希腊语", form: "hýdōr + génos", gloss: "生水者" }] },
  chronicle: { root: "chron", family: "Hellenic", lineage: [{ lang: "希腊语", form: "khroniká", gloss: "依时之事" }] },
  sympathy: { root: "path", family: "Hellenic", lineage: [{ lang: "希腊语", form: "sympátheia", gloss: "一起遭受" }] },
  patient: { root: "path", family: "Italic", lineage: [{ lang: "拉丁语", form: "patiēns", gloss: "正在遭受" }] },
  passion: { root: "path", family: "Italic", lineage: [{ lang: "拉丁语", form: "passiō", gloss: "受苦" }] },
  grammar: { root: "graph", family: "Hellenic", lineage: [{ lang: "希腊语", form: "grammatikḗ", gloss: "书写术" }] },
  privilege: { root: "leg", family: "Italic", lineage: [{ lang: "拉丁语", form: "prīvilēgium", gloss: "私人的法" }] },
  legislate: { root: "leg", family: "Italic", lineage: [{ lang: "拉丁语", form: "lēx + lātus", gloss: "把法带过来" }] },
  lexicon: { root: "leg", family: "Hellenic", lineage: [{ lang: "希腊语", form: "lexikón", gloss: "关于词的" }] },
  intelligent: { root: "leg", family: "Italic", lineage: [{ lang: "拉丁语", form: "intellegere", gloss: "在中间采集" }] },
  lecture: { root: "leg", family: "Italic", lineage: [{ lang: "拉丁语", form: "lēctūra", gloss: "采集，阅读" }] },
  collect: { root: "leg", family: "Italic", lineage: [{ lang: "拉丁语", form: "colligere", gloss: "一起采集" }] },
  memory: { root: "men", family: "Italic", lineage: [{ lang: "拉丁语", form: "memoria", gloss: "记得" }] },
  mention: { root: "men", family: "Italic", lineage: [{ lang: "拉丁语", form: "mentiō", gloss: "想起并说出" }] },
  mental: { root: "men", family: "Italic", lineage: [{ lang: "拉丁语", form: "mēns", gloss: "心智" }] },
  automatic: { root: "men", family: "Hellenic", lineage: [{ lang: "希腊语", form: "autómatos", gloss: "自己想动的" }] },
  music: { root: "men", family: "Hellenic", lineage: [{ lang: "希腊语", form: "mousikḗ", gloss: "缪斯的技艺" }] },
  courage: { root: "kerd", family: "Italic", lineage: [{ lang: "古法语", form: "corage", gloss: "心的状态" }] },
  credit: { root: "kerd", family: "Italic", lineage: [{ lang: "拉丁语", form: "crēdere", gloss: "把心交给；相信" }] },
  record: { root: "kerd", family: "Italic", lineage: [{ lang: "拉丁语", form: "recordārī", gloss: "再经过心" }] },
  cordial: { root: "kerd", family: "Italic", lineage: [{ lang: "拉丁语", form: "cordiālis", gloss: "出于心的" }] },
  economy: { root: "dem", family: "Hellenic", lineage: [{ lang: "希腊语", form: "oikonomía", gloss: "家的法" }] },
  domestic: { root: "dem", family: "Italic", lineage: [{ lang: "拉丁语", form: "domesticus", gloss: "家里的" }] },
  despot: { root: "dem", family: "Hellenic", lineage: [{ lang: "希腊语", form: "despótēs", gloss: "家的主人" }] },
  city: { root: "kei", family: "Italic", lineage: [{ lang: "拉丁语", form: "cīvitās", gloss: "公民的共同体" }] },
  civil: { root: "kei", family: "Italic", lineage: [{ lang: "拉丁语", form: "cīvīlis", gloss: "公民的" }] },
  police: { root: "kei", family: "Hellenic", lineage: [{ lang: "希腊语", form: "politeía", gloss: "城邦的安排" }] },
  politics: { root: "kei", family: "Hellenic", lineage: [{ lang: "希腊语", form: "politiká", gloss: "城邦之事" }] },
  culture: { root: "ker", family: "Italic", lineage: [{ lang: "拉丁语", form: "colere / cultūra", gloss: "耕种，照料" }] },
  create: { root: "ker", family: "Italic", lineage: [{ lang: "拉丁语", form: "creāre", gloss: "使生长" }] },
  crescent: { root: "ker", family: "Italic", lineage: [{ lang: "拉丁语", form: "crēscēns", gloss: "正在生长" }] },
  complete: { root: "pel", family: "Italic", lineage: [{ lang: "拉丁语", form: "complēre", gloss: "填满" }] },
  plenty: { root: "pel", family: "Italic", lineage: [{ lang: "拉丁语", form: "plēnitās", gloss: "充满" }] },
  plus: { root: "pel", family: "Italic", lineage: [{ lang: "拉丁语", form: "plūs", gloss: "更多" }] },
  full: { root: "pel", family: "Germanic", lineage: [{ lang: "古英语", form: "full", gloss: "满" }] },
  vacant: { root: "eu", family: "Italic", lineage: [{ lang: "拉丁语", form: "vacāns", gloss: "空着" }] },
  vanish: { root: "eu", family: "Italic", lineage: [{ lang: "拉丁语", form: "vānēscere", gloss: "变成空" }] },
  vain: { root: "eu", family: "Italic", lineage: [{ lang: "拉丁语", form: "vānus", gloss: "空的" }] },
  unique: { root: "oi", family: "Italic", lineage: [{ lang: "拉丁语", form: "ūnicus", gloss: "唯一的" }] },
  union: { root: "oi", family: "Italic", lineage: [{ lang: "拉丁语", form: "ūniō", gloss: "合一" }] },
  simple: { root: "sem", family: "Italic", lineage: [{ lang: "拉丁语", form: "simplus", gloss: "同一折，未翻倍" }] },
  similar: { root: "sem", family: "Italic", lineage: [{ lang: "拉丁语", form: "similis", gloss: "同一的" }] },
  assemble: { root: "sem", family: "Italic", lineage: [{ lang: "拉丁语", form: "assimulāre / ad + simul", gloss: "放到同一" }] },
  same: { root: "sem", family: "Germanic", lineage: [{ lang: "古诺斯语", form: "samr", gloss: "同一" }] },
  new: { root: "newo", family: "Germanic", lineage: [{ lang: "古英语", form: "nīwe", gloss: "新" }] },
  novel: { root: "newo", family: "Italic", lineage: [{ lang: "拉丁语", form: "novellus", gloss: "新的" }] },
  renovate: { root: "newo", family: "Italic", lineage: [{ lang: "拉丁语", form: "renovāre", gloss: "重新做成新的" }] },
  right: { root: "reg", family: "Germanic", lineage: [{ lang: "古英语", form: "riht", gloss: "直的，正确的" }] },
  royal: { root: "reg", family: "Italic", lineage: [{ lang: "拉丁语", form: "rēgālis", gloss: "王的" }] },
  direct: { root: "reg", family: "Italic", lineage: [{ lang: "拉丁语", form: "dīrectus", gloss: "被拉直的" }] },
  surge: { root: "reg", family: "Italic", lineage: [{ lang: "拉丁语", form: "surgere", gloss: "升直" }] },
  regular: { root: "reg", family: "Italic", lineage: [{ lang: "拉丁语", form: "rēgula", gloss: "直尺" }] },
  rectify: { root: "reg", family: "Italic", lineage: [{ lang: "拉丁语", form: "rēctificāre", gloss: "使直" }] },
  tension: { root: "ten", family: "Italic", lineage: [{ lang: "拉丁语", form: "tēnsiō", gloss: "拉伸" }] },
  attend: { root: "ten", family: "Italic", lineage: [{ lang: "拉丁语", form: "attendere", gloss: "把心拉伸向" }] },
  intend: { root: "ten", family: "Italic", lineage: [{ lang: "拉丁语", form: "intendere", gloss: "向内拉伸" }] },
  extend: { root: "ten", family: "Italic", lineage: [{ lang: "拉丁语", form: "extendere", gloss: "向外拉伸" }] },
  tone: { root: "ten", family: "Hellenic", lineage: [{ lang: "希腊语", form: "tónos", gloss: "弦的拉伸" }] },
  verse: { root: "wer", family: "Italic", lineage: [{ lang: "拉丁语", form: "versus", gloss: "翻转；诗行" }] },
  conversation: { root: "wer", family: "Italic", lineage: [{ lang: "拉丁语", form: "conversātiō", gloss: "一起转；交往" }] },
  emotion: { root: "meue", family: "Italic", lineage: [{ lang: "拉丁语", form: "ēmovēre", gloss: "移出去" }] },
  move: { root: "meue", family: "Italic", lineage: [{ lang: "拉丁语", form: "movēre", gloss: "移动" }] },
  moment: { root: "meue", family: "Italic", lineage: [{ lang: "拉丁语", form: "mōmentum", gloss: "使动的一点" }] },
  adventure: { root: "gwa", family: "Italic", lineage: [{ lang: "拉丁语", form: "advenīre", gloss: "向着走来的事" }] },
  invent: { root: "gwa", family: "Italic", lineage: [{ lang: "拉丁语", form: "invenīre", gloss: "走进而发现" }] },
  prevent: { root: "gwa", family: "Italic", lineage: [{ lang: "拉丁语", form: "praevenīre", gloss: "先走到" }] },
  intervene: { root: "gwa", family: "Italic", lineage: [{ lang: "拉丁语", form: "intervenīre", gloss: "走到中间" }] },
  revenue: { root: "gwa", family: "Italic", lineage: [{ lang: "法语", form: "revenir", gloss: "回来的东西" }] },
  data: { root: "do", family: "Italic", lineage: [{ lang: "拉丁语", form: "data", gloss: "被给出的" }] },
  donate: { root: "do", family: "Italic", lineage: [{ lang: "拉丁语", form: "dōnāre", gloss: "给予" }] },
  tradition: { root: "do", family: "Italic", lineage: [{ lang: "拉丁语", form: "trādere", gloss: "交过去" }] },
  traitor: { root: "do", family: "Italic", lineage: [{ lang: "拉丁语", form: "trāditor", gloss: "交出的人" }] },
  date: { root: "do", family: "Italic", lineage: [{ lang: "拉丁语", form: "data (littera)", gloss: "被给出的信；日期" }] },
  juror: { root: "yewes", family: "Italic", lineage: [{ lang: "拉丁语", form: "iūrātor", gloss: "宣誓者" }] },
  alternative: { root: "al", family: "Italic", lineage: [{ lang: "拉丁语", form: "alter", gloss: "另一个" }] },
  seminar: { root: "gen", family: "Italic", lineage: [{ lang: "拉丁语", form: "sēminārium", gloss: "苗圆，播种处" }] },
  robust: { root: "deru", family: "Italic", lineage: [{ lang: "拉丁语", form: "rōbustus", gloss: "像橡树的" }] },
  pendulum: { root: "ten", family: "Italic", lineage: [{ lang: "拉丁语", form: "pendēre", gloss: "悬挂" }] },
  gospel: { root: "bha", family: "Germanic", lineage: [{ lang: "古英语", form: "gōdspell", gloss: "好消息" }] },
  telescope: { root: "spek", family: "Hellenic", lineage: [{ lang: "希腊语", form: "têle + skopeîn", gloss: "看远" }] },
  imminent: { root: "men", family: "Italic", lineage: [{ lang: "拉丁语", form: "imminēre", gloss: "向内突出，逼近" }] },
  fabric: { root: "dhe", family: "Italic", lineage: [{ lang: "拉丁语", form: "fabrica", gloss: "作坊；构造" }] },
  cooperate: { root: "werg", family: "Italic", lineage: [{ lang: "拉丁语", form: "cooperārī", gloss: "一起工作" }] },
  description: { root: "graph", family: "Italic", lineage: [{ lang: "拉丁语", form: "dēscrībere", gloss: "写下，描出" }] },
  approximately: { root: "per", family: "Italic", lineage: [{ lang: "拉丁语", form: "approximāre", gloss: "靠近最近处" }] },
  authorize: { root: "ag", family: "Italic", lineage: [{ lang: "拉丁语", form: "auctor", gloss: "使增长者；作者" }] },
  navigation: { root: "wed", family: "Italic", lineage: [{ lang: "拉丁语", form: "nāvigātiō", gloss: "驾船" }] },
  pedestrian: { root: "ped", family: "Italic", lineage: [{ lang: "拉丁语", form: "pedester", gloss: "用脚的" }] },
  facilitate: { root: "dhe", family: "Italic", lineage: [{ lang: "拉丁语", form: "facilis", gloss: "做得了的" }] },
  infinity: { root: "oi", family: "Italic", lineage: [{ lang: "拉丁语", form: "īnfīnītus", gloss: "没有边界" }] },
  analyze: { root: "skei", family: "Hellenic", lineage: [{ lang: "希腊语", form: "analþin", gloss: "解开" }] },
  split: { root: "skei", family: "Germanic", lineage: [{ lang: "中古荷兰语", form: "splitten", gloss: "劈开" }] },
  presumably: { root: "kap", family: "Italic", lineage: [{ lang: "拉丁语", form: "praesūmere", gloss: "预先拿取" }] },
  indicate: { root: "deik", family: "Italic", lineage: [{ lang: "拉丁语", form: "indicare", gloss: "指向" }] },
  conflict: { root: "ag", family: "Italic", lineage: [{ lang: "拉丁语", form: "conflīgere", gloss: "一起碰击" }] },
  benefit: { root: "dhe", family: "Italic", lineage: [{ lang: "拉丁语", form: "benefactum", gloss: "做得好的事" }] },
  influential: { root: "pleu", family: "Italic", lineage: [{ lang: "拉丁语", form: "īnfluere", gloss: "流入" }] },
  reconcile: { root: "kerd", family: "Italic", lineage: [{ lang: "拉丁语", form: "reconciliāre", gloss: "再带到一起" }] },
  precede: { root: "wegh", family: "Italic", lineage: [{ lang: "拉丁语", form: "praecēdere", gloss: "走在前面" }] },
  collaborate: { root: "werg", family: "Italic", lineage: [{ lang: "拉丁语", form: "collabōrāre", gloss: "一起劳动" }] },
  principle: { root: "per", family: "Italic", lineage: [{ lang: "拉丁语", form: "prīncipium", gloss: "第一的抓住；开端" }] },
  meaning: { root: "men", family: "Germanic", lineage: [{ lang: "古英语", form: "mǣnan", gloss: "打算；表示" }] },
  mean: { root: "men", family: "Germanic", lineage: [{ lang: "古英语", form: "mǣnan", gloss: "意欲，表示" }] },
};
