import type { LangFamily, LineageStep } from "./types";

export type LemmaHint = {
  root: string;
  family: LangFamily;
  lineage: LineageStep[];
  stem?: string;
};

export const LEMMAS_A: Record<string, LemmaHint> = {
  be: { root: "es", family: "Germanic", lineage: [
    { lang: "原始印欧语", form: "*h₁es- / *bʰeuH-", gloss: "是；生长" },
    { lang: "原始日耳曼语", form: "*beuną / *immi", gloss: "是，成为" },
    { lang: "古英语", form: "bēon / eom / is", gloss: "是" },
  ]},
  am: { root: "es", family: "Germanic", lineage: [{ lang: "原始印欧语", form: "*h₁esmi", gloss: "我是" }, { lang: "古英语", form: "eom", gloss: "我是" }] },
  is: { root: "es", family: "Germanic", lineage: [{ lang: "原始印欧语", form: "*h₁esti", gloss: "他是" }, { lang: "古英语", form: "is", gloss: "是" }] },
  are: { root: "es", family: "Germanic", lineage: [{ lang: "古诺斯语", form: "eru", gloss: "是（复数）" }] },
  was: { root: "es", family: "Germanic", lineage: [{ lang: "原始印欧语", form: "*h₂wes-", gloss: "停留，居住" }, { lang: "古英语", form: "wæs", gloss: "曾是" }] },
  were: { root: "es", family: "Germanic", lineage: [{ lang: "古英语", form: "wǣron", gloss: "曾是（复数）" }] },
  been: { root: "bheu", family: "Germanic", lineage: [{ lang: "原始印欧语", form: "*bʰeuH-", gloss: "生长，成为" }, { lang: "古英语", form: "bēon", gloss: "成为" }] },
  being: { root: "bheu", family: "Germanic", lineage: [{ lang: "英语", form: "being", gloss: "存在者；存在" }] },
  exist: { root: "sta", family: "Italic", lineage: [
    { lang: "拉丁语", form: "exsistere", gloss: "站出来" },
    { lang: "ex- + sistere", form: "从站立中走出", gloss: "显现为在" },
  ]},
  existence: { root: "sta", family: "Italic", lineage: [{ lang: "拉丁语", form: "exsistentia", gloss: "站出来的状态" }] },
  essence: { root: "es", family: "Italic", lineage: [
    { lang: "原始印欧语", form: "*h₁es-", gloss: "是" },
    { lang: "拉丁语", form: "essentia", gloss: "是其所是" },
  ]},
  nature: { root: "gen", family: "Italic", lineage: [
    { lang: "原始印欧语", form: "*ǥenh₁-", gloss: "生育" },
    { lang: "拉丁语", form: "nātūra", gloss: "将要出生的东西；本性" },
  ]},
  origin: { root: "al", family: "Italic", lineage: [
    { lang: "拉丁语", form: "orīrī", gloss: "升起，出现" },
    { lang: "orīgō", form: "origo", gloss: "源头" },
  ]},
  original: { root: "al", family: "Italic", lineage: [{ lang: "拉丁语", form: "orīginālis", gloss: "源头的" }] },
  philosophy: { root: "phil", family: "Hellenic", lineage: [
    { lang: "希腊语", form: "philosophia", gloss: "对智慧的爱" },
    { lang: "philos + sophia", form: "亲爱 + 智慧", gloss: "不是占有，是朝向" },
  ]},
  spirit: { root: "speis", family: "Italic", lineage: [
    { lang: "原始印欧语", form: "*speis-", gloss: "吹" },
    { lang: "拉丁语", form: "spīritus", gloss: "呼吸，气息" },
    { lang: "古法语", form: "espirit", gloss: "精神" },
  ]},
  soul: { root: "ane", family: "Germanic", lineage: [
    { lang: "原始日耳曼语", form: "*saiwalō", gloss: "灵魂" },
    { lang: "古英语", form: "sāwol", gloss: "灵魂" },
  ]},
  mind: { root: "men", family: "Germanic", lineage: [
    { lang: "原始印欧语", form: "*men-", gloss: "想" },
    { lang: "古英语", form: "gemynd", gloss: "记忆，心智" },
  ]},
  heart: { root: "kerd", family: "Germanic", lineage: [
    { lang: "原始印欧语", form: "*ḱerd-", gloss: "心" },
    { lang: "古英语", form: "heorte", gloss: "心" },
  ]},
  true: { root: "deru", family: "Germanic", lineage: [
    { lang: "原始印欧语", form: "*deru-", gloss: "树；坚固" },
    { lang: "古英语", form: "trīewe", gloss: "忠实的，真的" },
  ]},
  truth: { root: "deru", family: "Germanic", lineage: [{ lang: "古英语", form: "trēowþ", gloss: "忠实，真实" }] },
  tree: { root: "deru", family: "Germanic", lineage: [{ lang: "古英语", form: "trēow", gloss: "树" }] },
  trust: { root: "deru", family: "Germanic", lineage: [{ lang: "古诺斯语", form: "traust", gloss: "信任，坚固" }] },
  word: { root: "werh", family: "Germanic", lineage: [
    { lang: "原始印欧语", form: "*werh₁-", gloss: "说出" },
    { lang: "古英语", form: "word", gloss: "词，话语" },
  ]},
  name: { root: "nomn", family: "Germanic", lineage: [
    { lang: "原始印欧语", form: "*h₃néh₃mn̥", gloss: "名字" },
    { lang: "古英语", form: "nama", gloss: "名" },
  ]},
  know: { root: "gno", family: "Germanic", lineage: [
    { lang: "原始印欧语", form: "*ǥneh₃-", gloss: "认识" },
    { lang: "古英语", form: "cnāwan", gloss: "知道" },
  ]},
  see: { root: "weid", family: "Germanic", lineage: [
    { lang: "原始印欧语", form: "*sekw- / 日耳曼 *sehwaną", gloss: "看" },
    { lang: "古英语", form: "sēon", gloss: "看见" },
  ]},
  idea: { root: "weid", family: "Hellenic", lineage: [
    { lang: "希腊语", form: "idea / eidos", gloss: "被看见的形状" },
    { lang: "柏拉图", form: "ἰδέα", gloss: "理念" },
  ]},
  history: { root: "weid", family: "Hellenic", lineage: [{ lang: "希腊语", form: "historía", gloss: "通过询问而得知的；史" }] },
  wise: { root: "weid", family: "Germanic", lineage: [{ lang: "古英语", form: "wīs", gloss: "知道的" }] },
  vision: { root: "weid", family: "Italic", lineage: [{ lang: "拉丁语", form: "vīsiō", gloss: "看见" }] },
  science: { root: "skei", family: "Italic", lineage: [
    { lang: "原始印欧语", form: "*skei-", gloss: "切开" },
    { lang: "拉丁语", form: "scīre / scientia", gloss: "知；被切开因而可说的知" },
  ]},
  decide: { root: "sek", family: "Italic", lineage: [{ lang: "拉丁语", form: "dēcīdere", gloss: "彻底切开" }] },
  decision: { root: "sek", family: "Italic", lineage: [{ lang: "拉丁语", form: "dēcīsiō", gloss: "切开的结果" }] },
  reason: { root: "leg", family: "Italic", lineage: [{ lang: "拉丁语", form: "ratiō", gloss: "计算，理由，比率" }] },
  logic: { root: "log", family: "Hellenic", lineage: [{ lang: "希腊语", form: "logikḗ", gloss: "关于 logos 的技艺" }] },
  language: { root: "wekw", family: "Italic", lineage: [{ lang: "拉丁语", form: "lingua", gloss: "舌；语言" }] },
  human: { root: "dhghem", family: "Italic", lineage: [
    { lang: "原始印欧语", form: "*dʰéǵʰōm", gloss: "大地" },
    { lang: "拉丁语", form: "homō / hūmānus", gloss: "地上者；人的" },
  ]},
  humble: { root: "dhghem", family: "Italic", lineage: [{ lang: "拉丁语", form: "humilis", gloss: "贴近泥土的" }] },
  man: { root: "manu", family: "Germanic", lineage: [{ lang: "古英语", form: "mann", gloss: "人" }] },
  woman: { root: "manu", family: "Germanic", lineage: [{ lang: "古英语", form: "wīfmann", gloss: "女性的人" }] },
  world: { root: "manu", family: "Germanic", lineage: [{ lang: "古英语", form: "weorold", gloss: "人的年龄；一世" }] },
  god: { root: "dyeu", family: "Germanic", lineage: [{ lang: "原始日耳曼语", form: "*gudą", gloss: "被祈求者；神" }] },
  divine: { root: "dyeu", family: "Italic", lineage: [{ lang: "拉丁语", form: "dīvīnus", gloss: "属天的" }] },
  day: { root: "dyeu", family: "Germanic", lineage: [{ lang: "古英语", form: "dæg", gloss: "白昼" }] },
  time: { root: "temp", family: "Germanic", lineage: [{ lang: "古英语", form: "tīma", gloss: "一段时间" }] },
  temporal: { root: "temp", family: "Italic", lineage: [{ lang: "拉丁语", form: "tempus", gloss: "时间，太阳穴" }] },
  life: { root: "gwei", family: "Germanic", lineage: [{ lang: "古英语", form: "līf", gloss: "生命" }] },
  live: { root: "gwei", family: "Germanic", lineage: [{ lang: "古英语", form: "libban", gloss: "活" }] },
  death: { root: "mer", family: "Germanic", lineage: [{ lang: "古英语", form: "dēaþ", gloss: "死" }] },
  die: { root: "mer", family: "Germanic", lineage: [{ lang: "古诺斯语", form: "deyja", gloss: "死" }] },
  mortal: { root: "mer", family: "Italic", lineage: [{ lang: "拉丁语", form: "mortālis", gloss: "有死的" }] },
  love: { root: "leubh", family: "Germanic", lineage: [{ lang: "古英语", form: "lufu", gloss: "爱" }] },
  believe: { root: "leubh", family: "Germanic", lineage: [{ lang: "古英语", form: "belṽfan", gloss: "把心交给" }] },
  good: { root: "deu", family: "Germanic", lineage: [{ lang: "古英语", form: "gōd", gloss: "好" }] },
  water: { root: "wed", family: "Germanic", lineage: [{ lang: "古英语", form: "wæter", gloss: "水" }] },
  fire: { root: "paewr", family: "Germanic", lineage: [{ lang: "古英语", form: "fỳr", gloss: "火" }] },
  earth: { root: "dhghem", family: "Germanic", lineage: [{ lang: "古英语", form: "eorþe", gloss: "地" }] },
  sun: { root: "dyeu", family: "Germanic", lineage: [{ lang: "古英语", form: "sunne", gloss: "日" }] },
  moon: { root: "me", family: "Germanic", lineage: [{ lang: "古英语", form: "mōna", gloss: "月；测量时间者" }] },
  month: { root: "me", family: "Germanic", lineage: [{ lang: "古英语", form: "mōnaþ", gloss: "月份" }] },
  star: { root: "leuk", family: "Germanic", lineage: [{ lang: "古英语", form: "steorra", gloss: "星" }] },
  night: { root: "nek", family: "Germanic", lineage: [{ lang: "古英语", form: "niht", gloss: "夜" }] },
  house: { root: "dem", family: "Germanic", lineage: [{ lang: "古英语", form: "hūs", gloss: "房屋" }] },
  home: { root: "kei", family: "Germanic", lineage: [{ lang: "古英语", form: "hām", gloss: "家园" }] },
  hand: { root: "man", family: "Germanic", lineage: [{ lang: "古英语", form: "hand", gloss: "手" }] },
  foot: { root: "ped", family: "Germanic", lineage: [{ lang: "古英语", form: "fōt", gloss: "脚" }] },
  eye: { root: "okw", family: "Germanic", lineage: [{ lang: "古英语", form: "ēage", gloss: "眼" }] },
  ear: { root: "kous", family: "Germanic", lineage: [{ lang: "古英语", form: "ēare", gloss: "耳" }] },
  head: { root: "kap", family: "Germanic", lineage: [{ lang: "古英语", form: "hēafod", gloss: "头" }] },
  one: { root: "oi", family: "Germanic", lineage: [{ lang: "古英语", form: "ān", gloss: "一" }] },
  two: { root: "oi", family: "Germanic", lineage: [{ lang: "古英语", form: "twā", gloss: "二" }] },
  three: { root: "oi", family: "Germanic", lineage: [{ lang: "古英语", form: "þrīe", gloss: "三" }] },
  i: { root: "es", family: "Germanic", lineage: [{ lang: "古英语", form: "ic", gloss: "我" }] },
  you: { root: "es", family: "Germanic", lineage: [{ lang: "古英语", form: "gē / þū", gloss: "你们 / 你" }] },
  we: { root: "es", family: "Germanic", lineage: [{ lang: "古英语", form: "wē", gloss: "我们" }] },
  they: { root: "es", family: "Germanic", lineage: [{ lang: "古诺斯语", form: "þeir", gloss: "他们" }] },
  the: { root: "deik", family: "Germanic", lineage: [{ lang: "古英语", form: "þē / sē", gloss: "那" }] },
  a: { root: "oi", family: "Germanic", lineage: [{ lang: "古英语", form: "ān", gloss: "一；任一" }] },
  an: { root: "oi", family: "Germanic", lineage: [{ lang: "古英语", form: "ān", gloss: "一" }] },
  and: { root: "sem", family: "Germanic", lineage: [{ lang: "古英语", form: "and", gloss: "并且" }] },
  or: { root: "eu", family: "Germanic", lineage: [{ lang: "古英语", form: "oþþe", gloss: "或者" }] },
  but: { root: "per", family: "Germanic", lineage: [{ lang: "古英语", form: "būtan", gloss: "在外；但是" }] },
  if: { root: "es", family: "Germanic", lineage: [{ lang: "古英语", form: "gif", gloss: "如果" }] },
  not: { root: "nek", family: "Germanic", lineage: [{ lang: "古英语", form: "nā / nōht", gloss: "不" }] },
  no: { root: "nek", family: "Germanic", lineage: [{ lang: "古英语", form: "nā", gloss: "不" }] },
  have: { root: "kap", family: "Germanic", lineage: [{ lang: "古英语", form: "habban", gloss: "抓住；有" }] },
  do: { root: "dhe", family: "Germanic", lineage: [{ lang: "古英语", form: "dōn", gloss: "做，放" }] },
  go: { root: "gwa", family: "Germanic", lineage: [{ lang: "古英语", form: "gān", gloss: "走" }] },
  come: { root: "gwa", family: "Germanic", lineage: [{ lang: "古英语", form: "cuman", gloss: "来" }] },
  think: { root: "men", family: "Germanic", lineage: [{ lang: "古英语", form: "încan", gloss: "想" }] },
  feel: { root: "sent", family: "Germanic", lineage: [{ lang: "古英语", form: "fēlan", gloss: "摸；感觉" }] },
  hear: { root: "kous", family: "Germanic", lineage: [{ lang: "古英语", form: "hīeran", gloss: "听" }] },
  say: { root: "wekw", family: "Germanic", lineage: [{ lang: "古英语", form: "secgan", gloss: "说" }] },
  speak: { root: "wekw", family: "Germanic", lineage: [{ lang: "古英语", form: "sprecan", gloss: "说话" }] },
  give: { root: "do", family: "Germanic", lineage: [{ lang: "古英语", form: "giefan", gloss: "给" }] },
  take: { root: "tag", family: "Germanic", lineage: [{ lang: "古诺斯语", form: "taka", gloss: "拿" }] },
  make: { root: "dhe", family: "Germanic", lineage: [{ lang: "古英语", form: "macian", gloss: "做" }] },
  stand: { root: "sta", family: "Germanic", lineage: [{ lang: "古英语", form: "standan", gloss: "站" }] },
  understand: { root: "sta", family: "Germanic", lineage: [{ lang: "古英语", form: "understandan", gloss: "站到下面" }] },
  will: { root: "wel", family: "Germanic", lineage: [{ lang: "古英语", form: "willan", gloss: "愿意" }] },
  can: { root: "gno", family: "Germanic", lineage: [{ lang: "古英语", form: "cunnan", gloss: "知道如何" }] },
  may: { root: "poti", family: "Germanic", lineage: [{ lang: "古英语", form: "mæg", gloss: "能够" }] },
  must: { root: "poti", family: "Germanic", lineage: [{ lang: "古英语", form: "mōste", gloss: "必须" }] },
  power: { root: "poti", family: "Italic", lineage: [{ lang: "古法语", form: "poeir", gloss: "能够" }] },
  possible: { root: "poti", family: "Italic", lineage: [{ lang: "拉丁语", form: "possibilis", gloss: "做得了的" }] },
  act: { root: "ag", family: "Italic", lineage: [{ lang: "拉丁语", form: "āctus / agere", gloss: "驱动；行为" }] },
  action: { root: "ag", family: "Italic", lineage: [{ lang: "拉丁语", form: "āctiō", gloss: "行动" }] },
  fact: { root: "dhe", family: "Italic", lineage: [{ lang: "拉丁语", form: "factum", gloss: "已做成的" }] },
  form: { root: "form", family: "Italic", lineage: [{ lang: "拉丁语", form: "fōrma", gloss: "模具，形状" }] },
  space: { root: "sta", family: "Italic", lineage: [{ lang: "拉丁语", form: "spatium", gloss: "间隔，场地" }] },
  intuition: { root: "spek", family: "Italic", lineage: [
    { lang: "拉丁语", form: "intuerī", gloss: "向内注视" },
    { lang: "in- + tuerī", form: "看", gloss: "不用推理的看见" },
  ]},
  inspire: { root: "speis", family: "Italic", lineage: [{ lang: "拉丁语", form: "īnspīrāre", gloss: "吹入" }] },
  inspiration: { root: "speis", family: "Italic", lineage: [{ lang: "拉丁语", form: "īnspīrātiō", gloss: "被吹入" }] },
  expire: { root: "speis", family: "Italic", lineage: [{ lang: "拉丁语", form: "exspīrāre", gloss: "把气呼出；断气" }] },
  conspiracy: { root: "speis", family: "Italic", lineage: [{ lang: "拉丁语", form: "conspīrāre", gloss: "一起呼吸；密谋" }] },
  universe: { root: "wer", family: "Italic", lineage: [{ lang: "拉丁语", form: "ūniversum", gloss: "转到一体的" }] },
  university: { root: "oi", family: "Italic", lineage: [{ lang: "拉丁语", form: "ūniversitās", gloss: "整体，共同体" }] },
  convert: { root: "wer", family: "Italic", lineage: [{ lang: "拉丁语", form: "convertere", gloss: "转过去" }] },
  reverse: { root: "wer", family: "Italic", lineage: [{ lang: "拉丁语", form: "revertere", gloss: "转回来" }] },
  educate: { root: "deuk", family: "Italic", lineage: [{ lang: "拉丁语", form: "ēducāre", gloss: "引出，养育" }] },
  education: { root: "deuk", family: "Italic", lineage: [{ lang: "拉丁语", form: "ēducātiō", gloss: "引出" }] },
  conduct: { root: "deuk", family: "Italic", lineage: [{ lang: "拉丁语", form: "condūcere", gloss: "一起引导" }] },
  produce: { root: "deuk", family: "Italic", lineage: [{ lang: "拉丁语", form: "prōdūcere", gloss: "向前引出" }] },
  reduce: { root: "deuk", family: "Italic", lineage: [{ lang: "拉丁语", form: "redūcere", gloss: "引回" }] },
  introduce: { root: "deuk", family: "Italic", lineage: [{ lang: "拉丁语", form: "intrōdūcere", gloss: "引入" }] },
  capture: { root: "kap", family: "Italic", lineage: [{ lang: "拉丁语", form: "captūra", gloss: "抓住" }] },
  capable: { root: "kap", family: "Italic", lineage: [{ lang: "拉丁语", form: "capāx", gloss: "装得下的" }] },
  accept: { root: "kap", family: "Italic", lineage: [{ lang: "拉丁语", form: "accipere", gloss: "接到自己这边" }] },
  concept: { root: "kap", family: "Italic", lineage: [{ lang: "拉丁语", form: "conceptus", gloss: "一起抓住；受孕" }] },
  perceive: { root: "kap", family: "Italic", lineage: [{ lang: "拉丁语", form: "percipere", gloss: "彻底抓住" }] },
  receive: { root: "kap", family: "Italic", lineage: [{ lang: "拉丁语", form: "recipere", gloss: "拿回来" }] },
  comprehend: { root: "ghend", family: "Italic", lineage: [{ lang: "拉丁语", form: "comprehendere", gloss: "一起抓住" }] },
};
