import type { Root } from "./types";

export const ROOTS: Root[] = [
  { id: "es", form: "*h₁es-", lang: "原始印欧语", gloss: "是，存在", glossEn: "to be", era: "约公元前 4000 年", kernel: "be", note: "系词的源头。英语 am / is / are / was 的深层骨架，存在最先作为一句判断说出。" },
  { id: "bheu", form: "*bʰeuH-", lang: "原始印欧语", gloss: "生长，成为，存在", glossEn: "to grow, become, be", era: "约公元前 4000 年", kernel: "be", note: "be 的完成体来源。拉丁 fui、希腊 physis、英语 be / bound / husband 都从「生长」走到「是」。" },
  { id: "speis", form: "*speis-", lang: "原始印欧语", gloss: "吹", glossEn: "to blow", era: "约公元前 4000 年", kernel: "breath", note: "气离开身体的那一下。拉丁 spiritus 本义呼吸，死亡被想象成气的出走，精神由此得名。" },
  { id: "sta", form: "*steh₂-", lang: "原始印欧语", gloss: "站立", glossEn: "to stand", era: "约公元前 4000 年", kernel: "stand", note: "使某物停在那里。state、stand、institute、system 都是「让它站住」的不同语法。" },
  { id: "weid", form: "*weid-", lang: "原始印欧语", gloss: "看见，由此：知道", glossEn: "to see, hence know", era: "约公元前 4000 年", kernel: "see", note: "印欧人把「看见」与「知道」叠成同一个词根。梵语 veda、拉丁 videre、英语 wise / idea / history 同源。" },
  { id: "gno", form: "*ǥneh₃-", lang: "原始印欧语", gloss: "认识", glossEn: "to know", era: "约公元前 4000 年", kernel: "know", note: "比看见更内在的知。know、cognition、ignore、noble 都从同一声「我认得」。" },
  { id: "wekw", form: "*wekw-", lang: "原始印欧语", gloss: "说话", glossEn: "to speak", era: "约公元前 4000 年", kernel: "speak", note: "声音被送出。拉丁 vox、希腊 epos、英语 voice / vocal / epic 都是口中的气取得形式。" },
  { id: "bha", form: "*bʰeh₂-", lang: "原始印欧语", gloss: "发光；说话", glossEn: "to shine; to speak", era: "约公元前 4000 年", kernel: "light", note: "光与言在此重叠：使黑暗中出现轮廓。fable、phone、photograph、fantasy 都是「让它显现」。" },
  { id: "wegh", form: "*weǵʰ-", lang: "原始印欧语", gloss: "走，运载", glossEn: "to go, transport", era: "约公元前 4000 年", kernel: "go", note: "道路与车辆的根。way、wagon、vehicle、via、voyage、obvious 都是被带走或把人带走。" },
  { id: "gwa", form: "*gʷeh₂-", lang: "原始印欧语", gloss: "走来", glossEn: "to come", era: "约公元前 4000 年", kernel: "go", note: "come、venture、adventure、revenue、intervene 都是「走到现场」。" },
  { id: "bher", form: "*bʰer-", lang: "原始印欧语", gloss: "拿，承载，生育", glossEn: "to carry, bear", era: "约公元前 4000 年", kernel: "carry", note: "双手托住。bear、birth、burden、fertile、metaphor 都是把一物从这里带到那里。" },
  { id: "kap", form: "*kap-", lang: "原始印欧语", gloss: "抓住", glossEn: "to grasp", era: "约公元前 4000 年", kernel: "grasp", note: "手合拢。capture、capable、have、accept、perceive 都是「拿到手」的精神化。" },
  { id: "ghend", form: "*ghend-", lang: "原始印欧语", gloss: "抓住，取得", glossEn: "to seize", era: "约公元前 4000 年", kernel: "grasp", note: "比 kap 更猛的一擎。comprehend、prey、prison 都是一把抓住后不再放开。" },
  { id: "sek", form: "*sek-", lang: "原始印欧语", gloss: "切开", glossEn: "to cut", era: "约公元前 4000 年", kernel: "cut", note: "刃走进连续体。section、segment、saw、risk 都留下一道切口。" },
  { id: "skei", form: "*skei-", lang: "原始印欧语", gloss: "切开，分开", glossEn: "to cut, split", era: "约公元前 4000 年", kernel: "cut", note: "科学 science 来自 scire「知」，而 scire 来自切开：知，就是把混茫分成可说的两边。" },
  { id: "yeug", form: "*yeug-", lang: "原始印欧语", gloss: "轭，接合", glossEn: "to join, yoke", era: "约公元前 4000 年", kernel: "join", note: "两头牲口被同一根横木拓住。yoga、join、conjugal、zygote 都是被绑在一起的命运。" },
  { id: "bhendh", form: "*bhendh-", lang: "原始印欧语", gloss: "捆绑", glossEn: "to bind", era: "约公元前 4000 年", kernel: "bind", note: "绳子的记忆。bind、band、bundle、husband 都是不让散开。" },
  { id: "do", form: "*deh₃-", lang: "原始印欧语", gloss: "给予", glossEn: "to give", era: "约公元前 4000 年", kernel: "give", note: "手向外张开。data 是「被给出的」，donate、endow、traitor（交出）都从这一掌。" },
  { id: "gen", form: "*ǥenh₁-", lang: "原始印欧语", gloss: "生育，产生", glossEn: "to give birth", era: "约公元前 4000 年", kernel: "birth", note: "让一个新的存在进入世界。genesis、nature、nation、kin、pregnant 都是「生出来」。" },
  { id: "mer", form: "*mer-", lang: "原始印欧语", gloss: "消磨，死亡", glossEn: "to die, to harm", era: "约公元前 4000 年", kernel: "die", note: "mortal、murder、nightmare 都记得肉体的限期。" },
  { id: "gwei", form: "*gʷei-", lang: "原始印欧语", gloss: "活着", glossEn: "to live", era: "约公元前 4000 年", kernel: "live", note: "bio-、zoo-、vital、quick（古义：活的）都是还没有停下来的运动。" },
  { id: "men", form: "*men-", lang: "原始印欧语", gloss: "想，心灵活动", glossEn: "to think", era: "约公元前 4000 年", kernel: "think", note: "mind、memory、mention、automatic、muse 都是内心的停留与返回。" },
  { id: "kerd", form: "*ḱerd-", lang: "原始印欧语", gloss: "心", glossEn: "heart", era: "约公元前 4000 年", kernel: "heart", note: "心是身体里的鼓。cordial、courage、credit、record 都把心当成可信的中心。" },
  { id: "leuk", form: "*leuk-", lang: "原始印欧语", gloss: "光，明亮", glossEn: "light, brightness", era: "约公元前 4000 年", kernel: "light", note: "light、lunar、lucid、illuminate 都是黑暗被撕开后留下的白色。" },
  { id: "wed", form: "*wed-", lang: "原始印欧语", gloss: "水", glossEn: "water", era: "约公元前 4000 年", kernel: "water", note: "water、undulate、whiskey（「生命之水」）、hydra、otter 都是流动的身体。" },
  { id: "dhghem", form: "*dʰéǵʰōm", lang: "原始印欧语", gloss: "大地", glossEn: "earth", era: "约公元前 4000 年", kernel: "earth", note: "人 human 与谦卑 humble 都来自 humus 泥土。人是地上的。" },
  { id: "paewr", form: "*peh₂wr̥", lang: "原始印欧语", gloss: "火", glossEn: "fire", era: "约公元前 4000 年", kernel: "fire", note: "fire、pyre、purify 都是燃烧把杂质送走。" },
  { id: "man", form: "*man-", lang: "原始印欧语", gloss: "手", glossEn: "hand", era: "约公元前 4000 年", kernel: "hand", note: "manual、command、emancipate、maintain 都是手在世界上的语法。" },
  { id: "ped", form: "*ped-", lang: "原始印欧语", gloss: "脚", glossEn: "foot", era: "约公元前 4000 年", kernel: "foot", note: "foot、pedestrian、expedition、pioneer 都从迈出的第一步开始。" },
  { id: "dem", form: "*dem-", lang: "原始印欧语", gloss: "房屋，家庭", glossEn: "house, household", era: "约公元前 4000 年", kernel: "house", note: "domestic、despot、timber、domain 都是有墙的秩序。" },
  { id: "me", form: "*meh₁-", lang: "原始印欧语", gloss: "度量", glossEn: "to measure", era: "约公元前 4000 年", kernel: "measure", note: "meter、month、moon、modest、medicine 都是给混沌一条尺。" },
  { id: "wer", form: "*wer-", lang: "原始印欧语", gloss: "转动，弯曲", glossEn: "to turn, bend", era: "约公元前 4000 年", kernel: "turn", note: "verse、convert、universe、wrench 都是一次转向：世界是转出来的。" },
  { id: "ten", form: "*ten-", lang: "原始印欧语", gloss: "伸展", glossEn: "to stretch", era: "约公元前 4000 年", kernel: "stretch", note: "tendon、tone、tension、tenuous、attend 都是被拉长的一条线。" },
  { id: "pel", form: "*pelh₁-", lang: "原始印欧语", gloss: "充满", glossEn: "to fill", era: "约公元前 4000 年", kernel: "fill", note: "full、plenty、plus、complete、supply 都是空被填到边缘。" },
  { id: "eu", form: "*h₁eu-", lang: "原始印欧语", gloss: "空，缺", glossEn: "empty, lacking", era: "约公元前 4000 年", kernel: "empty", note: "vain、vacant、vanish、waste 都是里面没有东西。" },
  { id: "oi", form: "*oi-no-", lang: "原始印欧语", gloss: "一", glossEn: "one", era: "约公元前 4000 年", kernel: "one", note: "one、any、ounce、unique、universe 都是不可再分的单位。" },
  { id: "sem", form: "*sem-", lang: "原始印欧语", gloss: "一，同一", glossEn: "one, together", era: "约公元前 4000 年", kernel: "one", note: "same、simple、assemble、similar、single 都是「还没有被分开」。" },
  { id: "deru", form: "*deru-", lang: "原始印欧语", gloss: "树；坚固；真实", glossEn: "tree; solid; true", era: "约公元前 4000 年", kernel: "true", note: "tree 与 true 是同一根：像树一样站着、不可弯曲的，才被称为真。" },
  { id: "deu", form: "*deu-", lang: "原始印欧语", gloss: "尊敬，善好", glossEn: "to honor, good", era: "约公元前 4000 年", kernel: "good", note: "dynamic 的力量与拉丁 bonus 的善在远处相关：善首先是旺盛。" },
  { id: "leubh", form: "*leubh-", lang: "原始印欧语", gloss: "爱，关切", glossEn: "to care, love", era: "约公元前 4000 年", kernel: "love", note: "love、libido、believe（把心托付给）都是被吸引而不能走开。" },
  { id: "poti", form: "*poti-", lang: "原始印欧语", gloss: "主人，有能力者", glossEn: "powerful lord", era: "约公元前 4000 年", kernel: "power", note: "power、possible、possess、despot、potency 都是「能把事情做成」。" },
  { id: "nomn", form: "*h₃néh₃mn̥", lang: "原始印欧语", gloss: "名字", glossEn: "name", era: "约公元前 4000 年", kernel: "name", note: "name、noun、nominate、anonymous 都是用声音把一个存在从混茫中叫出来。" },
  { id: "werg", form: "*werǵ-", lang: "原始印欧语", gloss: "做，工作", glossEn: "to do, work", era: "约公元前 4000 年", kernel: "work", note: "work、energy、organ、surgery、allergy 都是起作用的活动。" },
  { id: "sekw", form: "*sekw-", lang: "原始印欧语", gloss: "跟随", glossEn: "to follow", era: "约公元前 4000 年", kernel: "follow", note: "sequence、second、social、pursue、sign 都是跟在某物后面。" },
  { id: "deik", form: "*deik-", lang: "原始印欧语", gloss: "指出，显示", glossEn: "to show, pronounce", era: "约公元前 4000 年", kernel: "show", note: "digit、token、paradigm、dictionary、judge 都是用手指着说「就是这个」。" },
  { id: "dhe", form: "*dʰeh₁-", lang: "原始印欧语", gloss: "放置，使成立", glossEn: "to set, put", era: "约公元前 4000 年", kernel: "put", note: "do、deed、fact、thesis、theme、condition 都是把某物放到世界里，使它成立。" },
  { id: "pleu", form: "*pleu-", lang: "原始印欧语", gloss: "流动，漂浮", glossEn: "to flow, float", era: "约公元前 4000 年", kernel: "flow", note: "flow、fleet、fly、pulmonary、pluvial 都是不停留。" },
  { id: "ker", form: "*ker-", lang: "原始印欧语", gloss: "生长，角", glossEn: "to grow, horn", era: "约公元前 4000 年", kernel: "grow", note: "cereal、create、crescent、horn、unicorn 都是从一点往外长。" },
  { id: "wel", form: "*wel-", lang: "原始印欧语", gloss: "愿望，意愿", glossEn: "to wish, will", era: "约公元前 4000 年", kernel: "wish", note: "will、volunteer、voluptuous、wealth 都是心里倾向某物。" },
  { id: "steg", form: "*(s)teg-", lang: "原始印欧语", gloss: "覆盖", glossEn: "to cover", era: "约公元前 4000 年", kernel: "cover", note: "thatch、protect、detect、toga、deck 都是把暴露的东西藏起来或揭开。" },
  { id: "yewes", form: "*h₂yew-", lang: "原始印欧语", gloss: "法，仪式上的正确", glossEn: "law, ritual right", era: "约公元前 4000 年", kernel: "law", note: "just、jury、injury、perjury 都是被仪式固定下来的「应当」。" },
  { id: "dyeu", form: "*dyeu-", lang: "原始印欧语", gloss: "照耀的天空，神", glossEn: "to shine; sky god", era: "约公元前 4000 年", kernel: "sky", note: "Zeus、Jupiter、divine、Tuesday、day 都是白天那片发光的天。" },
  { id: "manu", form: "*manu-", lang: "原始印欧语", gloss: "人，男人", glossEn: "man", era: "约公元前 4000 年", kernel: "man", note: "man、Mensch、Manu 都是能思考的那种存在。human 则来自泥土。" },
  { id: "werh", form: "*werh₁-", lang: "原始印欧语", gloss: "说出", glossEn: "to speak", era: "约公元前 4000 年", kernel: "word", note: "word、verb、rhetoric、irony 都是被排列的声音，使世界可被讲述。" },
  { id: "ag", form: "*h₂eǵ-", lang: "原始印欧语", gloss: "驱赶，驱动", glossEn: "to drive", era: "约公元前 4000 年", kernel: "drive", note: "act、agent、agony、ambassador、strategy 都是使某物开始运动。" },
  { id: "deuk", form: "*deuk-", lang: "原始印欧语", gloss: "引导", glossEn: "to lead", era: "约公元前 4000 年", kernel: "lead", note: "duke、conduct、educate、subdue 都是把另一个存在带向某处。" },
  { id: "spek", form: "*speḱ-", lang: "原始印欧语", gloss: "注视", glossEn: "to observe", era: "约公元前 4000 年", kernel: "see", note: "spectacle、species、inspect、bishop、spy 都是目光停在某物上。" },
  { id: "sent", form: "*sent-", lang: "原始印欧语", gloss: "走；感觉", glossEn: "to go, to feel", era: "约公元前 4000 年", kernel: "feel", note: "send、sense、sentence、consent 都是内心跟着走。" },
  { id: "tag", form: "*tag-", lang: "原始印欧语", gloss: "触碰", glossEn: "to touch", era: "约公元前 4000 年", kernel: "touch", note: "tact、tangible、contact、integrity 都是两物相碰或尚未破损。" },
  { id: "reg", form: "*h₃reǵ-", lang: "原始印欧语", gloss: "伸直，治理", glossEn: "to move in a straight line", era: "约公元前 4000 年", kernel: "rule", note: "rex、royal、right、direct、regime、surge 都是一条被拉直的线。" },
  { id: "newo", form: "*néwo-", lang: "原始印欧语", gloss: "新的", glossEn: "new", era: "约公元前 4000 年", kernel: "new", note: "new、novel、renovate、neophyte 都是刚刚出现、还没有被用旧。" },
  { id: "ed", form: "*h₁ed-", lang: "原始印欧语", gloss: "吃", glossEn: "to eat", era: "约公元前 4000 年", kernel: "eat", note: "eat、edible、comestible、obese 都是把世界放进身体。" },
  { id: "swep", form: "*swep-", lang: "原始印欧语", gloss: "睡眠", glossEn: "to sleep", era: "约公元前 4000 年", kernel: "sleep", note: "sleep、hypnosis、insomniac 都是意识暂时退场。" },
  { id: "leg", form: "*leǵ-", lang: "原始印欧语", gloss: "收集；说话", glossEn: "to collect, speak", era: "约公元前 4000 年", kernel: "speak", note: "logos 是被收集起来的言。logic、legend、lexicon、intelligent 都是把散落的捡起来。" },
  { id: "gerbh", form: "*gerbh-", lang: "原始印欧语", gloss: "抓刻", glossEn: "to scratch", era: "约公元前 4000 年", kernel: "write", note: "grammar、graphic、carve、crab 都是在表面上留下痕迹。" },
  { id: "pag", form: "*paǵ-", lang: "原始印欧语", gloss: "固定，钉住", glossEn: "to fasten", era: "约公元前 4000 年", kernel: "bind", note: "peace、pact、page、propaganda、peasant 都是被钉牢的约定。" },
  { id: "per", form: "*per-", lang: "原始印欧语", gloss: "向前，穿过", glossEn: "forward, through", era: "约公元前 4000 年", kernel: "go", note: "prime、first、from、experience、fear 都带着「穿过」的方向。" },
  { id: "kei", form: "*ḱei-", lang: "原始印欧语", gloss: "躺下，定居", glossEn: "to lie, settle", era: "约公元前 4000 年", kernel: "house", note: "city、civic、cemetery、incite 都与安放身体的地点有关。" },
  { id: "gher", form: "*gher-", lang: "原始印欧语", gloss: "抓住；围住；渴望", glossEn: "to grasp, enclose, yearn", era: "约公元前 4000 年", kernel: "grasp", note: "garden、yard、choir、yearn 都是圈出一块，并朝它走去。" },
  { id: "bheidh", form: "*bʰeidh-", lang: "原始印欧语", gloss: "信任，劝服", glossEn: "to trust, persuade", era: "约公元前 4000 年", kernel: "trust", note: "faith、fidelity、federal、defy、confide 都是把身体交给另一个人。" },
  { id: "kous", form: "*ḱous-", lang: "原始印欧语", gloss: "听", glossEn: "to hear", era: "约公元前 4000 年", kernel: "hear", note: "hear、acoustic、show 的远亲。听是让世界进入而不去抓它。" },
  { id: "okw", form: "*h₃ekʷ-", lang: "原始印欧语", gloss: "眼", glossEn: "eye", era: "约公元前 4000 年", kernel: "see", note: "eye、ocular、optics、window（风之眼）都是身体上的开口。" },
  { id: "ane", form: "*h₂enh₁-", lang: "原始印欧语", gloss: "呼吸", glossEn: "to breathe", era: "约公元前 4000 年", kernel: "breath", note: "animal、animus、atmosphere 的 anima 都是那口使肉体成为活物的气。" },
  { id: "al", form: "*h₂el-", lang: "原始印欧语", gloss: "生长，养育", glossEn: "to grow, nourish", era: "约公元前 4000 年", kernel: "grow", note: "old、adult、altitude、abolish、haughty 都与往上长有关。" },
  { id: "meue", form: "*meue-", lang: "原始印欧语", gloss: "推开，移动", glossEn: "to push away", era: "约公元前 4000 年", kernel: "go", note: "move、motion、moment、emotion、mutiny 都是位置不再保持。" },
  { id: "ye", form: "*yeh₁-", lang: "原始印欧语", gloss: "投掷", glossEn: "to throw", era: "约公元前 4000 年", kernel: "drive", note: "ject、eject、adjacent、jet 都是被抛出的东西。" },
  { id: "nek", form: "*nek-", lang: "原始印欧语", gloss: "死亡，伤害", glossEn: "death, harm", era: "约公元前 4000 年", kernel: "die", note: "noxious、innocent、necrosis、pernicious 都是生命被碰到的边缘。" },
  { id: "sak", form: "*sak-", lang: "原始印欧语", gloss: "使神圣", glossEn: "to sanctify", era: "约公元前 4000 年", kernel: "law", note: "sacred、sacrifice、saint、consecrate 都是被从日常里单独分出。" },
  { id: "sol", form: "*sol-", lang: "原始印欧语", gloss: "完整", glossEn: "whole", era: "约公元前 4000 年", kernel: "fill", note: "solid、save、salute、catholic（katholikos 希腊「普遍」）附近的完整感。safe 来自拉丁 salvus。" },
  { id: "temp", form: "*temp-", lang: "原始印欧语", gloss: "拉伸，时间", glossEn: "to stretch; time", era: "约公元前 3500 年", kernel: "time", note: "tempus 或许是被拉伸的一段。time、temple、contemplate 都是划出的间隔。" },
  { id: "form", form: "forma", lang: "拉丁语", gloss: "形状，模具", glossEn: "shape, mold", era: "约公元前 200 年", kernel: "put", note: "form 在拉丁语里是模具。form、inform、reform、formula 都是把质料倒进一个轮廓。" },
  { id: "log", form: "λόγος", lang: "古希腊语", gloss: "言，理，采集", glossEn: "word, reason, gathering", era: "约公元前 800 年", kernel: "speak", note: "logos 是被采集的言，也是世界可被理解的秩序。logic、biology、prologue 都是言把事物收拢。" },
  { id: "phil", form: "φίλος", lang: "古希腊语", gloss: "亲爱", glossEn: "beloved", era: "约公元前 800 年", kernel: "love", note: "philosophy 是「爱智慧」：不是占有智慧，是朝它走去而不能停止。" },
  { id: "psych", form: "ψυχή", lang: "古希腊语", gloss: "呼吸，灵魂", glossEn: "breath, soul", era: "约公元前 800 年", kernel: "breath", note: "psyche 本是一口气。心理学是对这口不可见之气的近代命名。" },
  { id: "cosm", form: "κόσμος", lang: "古希腊语", gloss: "秩序，世界，妆饰", glossEn: "order, world, ornament", era: "约公元前 800 年", kernel: "put", note: "宇宙首先是被安排好的。cosmetic 与 cosmos 同源：都是给混乱一张脸。" },
  { id: "graph", form: "γράφειν", lang: "古希腊语", gloss: "刮写", glossEn: "to scratch, write", era: "约公元前 800 年", kernel: "write", note: "写是在表面上受伤。photograph、grammar、telegraph 都是留下的痕迹。" },
  { id: "theos", form: "θεός", lang: "古希腊语", gloss: "神", glossEn: "god", era: "约公元前 800 年", kernel: "sky", note: "enthusiasm 本义「神在里面」。theology 是对不可见者的言说。" },
  { id: "path", form: "πάθος", lang: "古希腊语", gloss: "遭受，感受", glossEn: "suffering, feeling", era: "约公元前 800 年", kernel: "feel", note: "pathos、sympathy、patient 都是让某事发生在自己身上，而不是去做它。" },
  { id: "chron", form: "χρόνος", lang: "古希腊语", gloss: "时间", glossEn: "time", era: "约公元前 800 年", kernel: "time", note: "Chronos 吞食自己的孩子。chronic、chronicle、anachronism 都是被时间咬住。" },
  { id: "geo", form: "γῆ", lang: "古希腊语", gloss: "大地", glossEn: "earth", era: "约公元前 800 年", kernel: "earth", note: "geo- 是脚底下那一层。geometry 本是量地。" },
  { id: "hydr", form: "ὕδωρ", lang: "古希腊语", gloss: "水", glossEn: "water", era: "约公元前 800 年", kernel: "water", note: "hydrogen 是「生水者」。水在希腊语里始终是质料的隐喻。" },
  { id: "bios", form: "βίος", lang: "古希腊语", gloss: "生命（人类的生活方式）", glossEn: "life, manner of living", era: "约公元前 800 年", kernel: "live", note: "希腊人区分 bios（有叙事的生活）与 zoe（单纯活着）。biology 后来把二者混为一谈。" },
  { id: "unk", form: "—", lang: "语源未明", gloss: "形态可辨，源头漫漩", glossEn: "etymon uncertain", era: "层层借用之后", kernel: "name", note: "有的词经过太多口耳，源头只剩下形状。我们仍可以从形态与意义里，摸到它最稳定的那一层。" },
];

export const ROOT_BY_ID: Record<string, Root> = Object.fromEntries(ROOTS.map((r) => [r.id, r]));
