/** Productive English stems → root id */
export const STEMS: Record<string, string> = {
  // see / know / show
  spec: "spek", spic: "spek", spect: "spek", scop: "spek", vis: "weid", vid: "weid",
  view: "weid", wise: "weid", ide: "weid", idea: "weid", hist: "weid", wit: "weid",
  gnos: "gno", gnot: "gno", gnor: "gno", cogn: "gno", not: "gno", nob: "gno",
  dict: "deik", dic: "deik", digit: "deik", token: "deik", dica: "deik",
  // speak / word / logos
  voc: "wekw", vok: "wekw", voke: "wekw", voice: "wekw", vocat: "wekw",
  log: "log", loqu: "leg", locut: "leg", lect: "leg", leg: "leg", lex: "leg",
  verb: "werh", word: "werh", rhetor: "werh", fabl: "bha", fam: "bha",
  phon: "bha", phem: "bha", phant: "bha", fan: "bha",
  graph: "graph", gram: "graph", graf: "gerbh", scrib: "gerbh", script: "gerbh",
  // breath / spirit / psyche
  spir: "speis", spirit: "speis", spirat: "speis",
  anim: "ane", psyche: "psych", psych: "psych",
  // be / stand / put
  ess: "es", sent: "es", ent: "es",
  sta: "sta", stat: "sta", stit: "sta", sist: "sta", stanc: "sta",
  thes: "dhe", thet: "dhe", them: "dhe", fact: "dhe", fect: "dhe", fic: "dhe",
  fac: "dhe", fy: "dhe", feat: "dhe", do: "dhe", deed: "dhe",
  form: "form", formul: "form",
  cosm: "cosm", cosmos: "cosm",
  // go / come / lead / drive
  via: "wegh", voy: "wegh", veh: "wegh", way: "wegh", vag: "wegh",
  ven: "gwa", vent: "gwa", venu: "gwa",
  duc: "deuk", duct: "deuk", duke: "deuk",
  act: "ag", ag: "ag", ig: "ag", agon: "ag",
  migr: "meue", mot: "meue", mov: "meue", mob: "meue", moment: "meue",
  ced: "wegh", cess: "wegh", ceed: "wegh",
  ject: "ye", jac: "ye", jet: "ye",
  // carry / grasp / give / bind
  fer: "bher", lat: "bher", gest: "bher", ger: "bher",
  cap: "kap", capt: "kap", cept: "kap", ceiv: "kap", cip: "kap", cup: "kap",
  prehend: "ghend", pris: "ghend", prehens: "ghend",
  don: "do", dat: "do", dos: "do", dow: "do", dit: "do",
  junct: "yeug", join: "yeug", jug: "yeug", zyg: "yeug", yog: "yeug",
  bind: "bhendh", bond: "bhendh", band: "bhendh", bund: "bhendh",
  pact: "pag", pac: "pag", peac: "pag", page: "pag",
  fid: "bheidh", feder: "bheidh", faith: "bheidh",
  // cut / rule / stretch / turn
  sec: "sek", sect: "sek", seg: "sek",
  sci: "skei", scind: "skei", sciss: "skei",
  tom: "skei", tmes: "skei",
  crit: "skei", cris: "skei",
  rect: "reg", reg: "reg", roy: "reg", rex: "reg", rig: "reg",
  tend: "ten", tens: "ten", tent: "ten", ten: "ten", tin: "ten", tain: "ten",
  tone: "ten", ton: "ten",
  vert: "wer", vers: "wer", vor: "wer",
  // birth / die / live / grow
  gen: "gen", gener: "gen", gn: "gen", nat: "gen", nasc: "gen", nai: "gen",
  mort: "mer", mori: "mer", morbid: "mer",
  vit: "gwei", viv: "gwei", bio: "bios", zo: "gwei", vital: "gwei",
  cresc: "ker", cret: "ker", crea: "ker", cereal: "ker",
  alt: "al", ol: "al", adult: "al",
  // think / heart / feel / hear
  ment: "men", mem: "men", min: "men", mn: "men", mus: "men",
  cord: "kerd", cour: "kerd", cred: "kerd", heart: "kerd",
  path: "path", pass: "path", pati: "path",
  sens: "sent", senti: "sent",
  aud: "kous", audi: "kous", acou: "kous",
  tact: "tag", tang: "tag", ting: "tag", tig: "tag",
  // light / water / earth / fire / sky
  luc: "leuk", lumin: "leuk", lust: "leuk", lux: "leuk", lun: "leuk",
  phot: "bha", phos: "bha",
  aqu: "wed", hydr: "hydr", und: "wed", water: "wed",
  geo: "geo", terr: "dhghem", hum: "dhghem", chthon: "dhghem",
  pyr: "paewr", ign: "paewr", flam: "paewr",
  dei: "dyeu", div: "dyeu", the: "theos", theos: "theos", jou: "dyeu",
  // hand / foot / house / measure / name
  man: "man", manu: "man", mand: "man",
  ped: "ped", pod: "ped", pus: "ped",
  dom: "dem", domest: "dem", despot: "dem",
  metr: "me", mens: "me", meas: "me", modest: "me", medi: "me",
  nom: "nomn", nym: "nomn", nomin: "nomn",
  // one / true / love / power / time / new
  uni: "oi", un: "oi", one: "oi",
  simil: "sem", sembl: "sem", simpl: "sem", sing: "sem",
  tru: "deru", tre: "deru", trust: "deru", dur: "deru",
  am: "leubh", amor: "leubh", amat: "leubh", phil: "phil",
  pot: "poti", poss: "poti", poten: "poti",
  tempor: "temp", chron: "chron",
  nov: "newo", neo: "newo", new: "newo",
  // work / cover / law / fill / empty / eat
  erg: "werg", urg: "werg", org: "werg", work: "werg",
  teg: "steg", tect: "steg", prote: "steg",
  jur: "yewes", just: "yewes", judic: "yewes",
  ple: "pel", plen: "pel", plet: "pel", ply: "pel", plus: "pel",
  vac: "eu", van: "eu", void: "eu",
  ed: "ed", es: "ed", vorac: "ed",
  dorm: "swep", somn: "swep", hypn: "swep",
  // follow / sequence
  sequ: "sekw", secut: "sekw", sue: "sekw", soci: "sekw",
  // misc productive
  port: "wegh",
  struct: "sta", stru: "sta",
  rupt: "sek",
  solv: "eu", solut: "eu",
  pend: "ten", pens: "ten", pond: "ten",
  mit: "meue", miss: "meue",
  pos: "dhe", posit: "dhe", pound: "dhe", pose: "dhe",
  press: "per", prim: "per", prin: "per",
  part: "per", par: "per",
  quir: "gno", quer: "gno", quest: "gno",
  serv: "steg",
  sign: "sekw",
  spectat: "spek",
  spirac: "speis",
  clud: "steg", clus: "steg", clos: "steg",
  flu: "pleu", flux: "pleu",
  flect: "wer", flex: "wer",
  fract: "sek", frag: "sek",
  fund: "pleu", fus: "pleu",
  grad: "ped", gress: "ped",
  her: "pag", hes: "pag",
  loc: "sta",
  lucent: "leuk",
  merg: "wed",
  mut: "meue",
  nunci: "wekw", nounc: "wekw",
  ori: "al", orig: "al",
  pel: "ag", puls: "ag",
  pet: "per",
  plic: "pel", plex: "pel",
  preci: "per",
  priv: "per",
  propri: "per",
  pung: "sek", punct: "sek",
  put: "skei",
  rad: "reg", ras: "reg",
  rap: "ghend",
  rid: "bha",
  rog: "reg",
  sal: "gwa", sult: "gwa",
  scend: "ped",
  sed: "sta", sess: "sta", sid: "sta",
  semin: "gen",
  sen: "al",
  simila: "sem",
  son: "bha",
  spond: "bheidh", spons: "bheidh",
  strain: "ten", strict: "ten", string: "ten",
  sum: "kap", sumpt: "kap",
  surg: "reg",
  termin: "ten",
  test: "deik",
  tex: "yeug", text: "yeug",
  therm: "paewr",
  tort: "wer",
  tract: "wegh", treat: "wegh",
  trib: "do",
  trud: "ag",
  turb: "wer",
  urb: "kei",
  ut: "kap", us: "kap",
  vad: "wegh",
  val: "poti", vail: "poti",
  vest: "steg",
  vic: "poti", vinc: "poti", vict: "poti",
  vig: "gwei",
  vol: "wel", volunt: "wel",
  volv: "wer", volut: "wer",
  morph: "form",
  anthrop: "dhghem",
  hydra: "hydr",
  patho: "path",
  phob: "path",
  tomy: "skei",
  logy: "log",
  sophy: "phil",
  nomy: "nomn",
  crac: "poti",
  arch: "reg",
  dem: "dem",
  popul: "manu",
  civ: "kei",
  poli: "kei",
};

/** Longer multi-letter stems checked first */
export const STEM_KEYS = Object.keys(STEMS).sort((a, b) => b.length - a.length);
